# Generated by Django 5.0.6 on 2024-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='کد فعالسازی'),
        ),
    ]
