# Generated by Django 5.0.6 on 2024-06-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_activate_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activate_code',
        ),
    ]
