# Generated by Django 5.0 on 2024-07-31 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('count', models.IntegerField(verbose_name='تعداد')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Installment_id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, editable=False, unique=True, verbose_name='شناسه اقساط')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('installments', models.IntegerField(default=12, verbose_name='تعداد اقساط')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_done', models.BooleanField(default=False, verbose_name='اتمام اقساط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('product_name', models.ManyToManyField(max_length=200, to='installments.product', verbose_name='نام کالا')),
            ],
        ),
    ]
