# Generated by Django 5.0 on 2024-07-31 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_installment', models.BigIntegerField(auto_created=True, db_index=True, editable=False, unique=True, verbose_name='شناسه قسط')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ هر قسط')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('installments_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installments.installment', verbose_name='اطلاعات اقساط')),
            ],
        ),
    ]
