# Generated by Django 5.0.6 on 2024-07-19 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='installment_date',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='installment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='اتمام اقساط'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment_id',
            field=models.BigIntegerField(auto_created=True, blank=True, editable=False, unique=True, verbose_name='شناسه پرداخت'),
        ),
    ]
