# Generated by Django 5.0 on 2024-07-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0003_alter_installmentdetail_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentdetail',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
