# Generated by Django 5.0.6 on 2024-07-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0005_remove_installment_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('count', models.IntegerField(verbose_name='تعداد')),
            ],
        ),
        migrations.RemoveField(
            model_name='installment',
            name='product_name',
        ),
        migrations.AddField(
            model_name='installment',
            name='product_name',
            field=models.ManyToManyField(max_length=200, to='installments.product', verbose_name='کالا'),
        ),
    ]
