# Generated by Django 5.0.7 on 2025-03-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebars',
            name='position',
            field=models.IntegerField(default=0, max_length=50, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='sidebars',
            name='slug',
            field=models.CharField(blank=True, help_text='اگر قصد دارید فقط همین URL باشد حتما قبل و بعد آن "/" قرار دهید.', max_length=100, unique=True, verbose_name='عنوان در url'),
        ),
    ]
