# Generated by Django 5.0.7 on 2025-03-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sidebars_position_alter_sidebars_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebars',
            name='position',
            field=models.IntegerField(max_length=50, verbose_name='ترتیب نمایش'),
        ),
    ]
