# Generated by Django 5.0.7 on 2025-07-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sidebars_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebars',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='فقط به مدیر نمایش داده میشود.', verbose_name='فقط مدیریت'),
        ),
        migrations.AlterField(
            model_name='sidebars',
            name='position',
            field=models.IntegerField(verbose_name='ترتیب نمایش'),
        ),
    ]
